"""initial behavioral schema

Revision ID: 4be282d73a12
Revises:
Create Date: 2026-09-13 07:21:57.914920

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

import smorx_behavior.db.types

# revision identifiers, used by Alembic.
revision: str = "4be282d73a12"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "projects",
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("slug", sa.String(length=120), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("meta", sa.JSON(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            smorx_behavior.db.types.UTCDateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            smorx_behavior.db.types.UTCDateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_projects")),
        sa.UniqueConstraint("slug", name=op.f("uc_projects_slug")),
    )
    op.create_table(
        "constitutions",
        sa.Column("project_id", sa.Uuid(), nullable=False),
        sa.Column("title", sa.String(length=300), nullable=False),
        sa.Column("statement", sa.Text(), nullable=True),
        sa.Column("status", sa.String(length=40), nullable=False),
        sa.Column("owner_scope", sa.String(length=60), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("locked", sa.Boolean(), nullable=False),
        sa.Column("ratified_at", smorx_behavior.db.types.UTCDateTime(timezone=True), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            smorx_behavior.db.types.UTCDateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            smorx_behavior.db.types.UTCDateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["project_id"], ["projects.id"], name=op.f("fk_constitutions_project_id_projects")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_constitutions")),
    )
    op.create_table(
        "repositories",
        sa.Column("project_id", sa.Uuid(), nullable=False),
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("url", sa.String(length=500), nullable=True),
        sa.Column("default_branch", sa.String(length=255), nullable=False),
        sa.Column("vcs", sa.String(length=50), nullable=False),
        sa.Column(
            "last_inspected_at", smorx_behavior.db.types.UTCDateTime(timezone=True), nullable=True
        ),
        sa.Column("meta", sa.JSON(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            smorx_behavior.db.types.UTCDateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            smorx_behavior.db.types.UTCDateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["project_id"], ["projects.id"], name=op.f("fk_repositories_project_id_projects")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_repositories")),
    )
    op.create_table(
        "changes",
        sa.Column("repository_id", sa.Uuid(), nullable=False),
        sa.Column("external_id", sa.String(length=100), nullable=True),
        sa.Column("commit_sha", sa.String(length=64), nullable=True),
        sa.Column("author", sa.String(length=200), nullable=True),
        sa.Column("title", sa.String(length=400), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("status", sa.String(length=40), nullable=False),
        sa.Column("changed_at", smorx_behavior.db.types.UTCDateTime(timezone=True), nullable=True),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("locked", sa.Boolean(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            smorx_behavior.db.types.UTCDateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            smorx_behavior.db.types.UTCDateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["repository_id"],
            ["repositories.id"],
            name=op.f("fk_changes_repository_id_repositories"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_changes")),
    )
    op.create_table(
        "constitution_claims",
        sa.Column("constitution_id", sa.Uuid(), nullable=False),
        sa.Column("category", sa.String(length=60), nullable=False),
        sa.Column("rule", sa.Text(), nullable=False),
        sa.Column("severity", sa.String(length=20), nullable=False),
        sa.Column("position", sa.Integer(), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("locked", sa.Boolean(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            smorx_behavior.db.types.UTCDateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            smorx_behavior.db.types.UTCDateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["constitution_id"],
            ["constitutions.id"],
            name=op.f("fk_constitution_claims_constitution_id_constitutions"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_constitution_claims")),
    )
    op.create_table(
        "dependencies",
        sa.Column("repository_id", sa.Uuid(), nullable=False),
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("kind", sa.String(length=40), nullable=False),
        sa.Column("version_spec", sa.String(length=120), nullable=True),
        sa.Column("ecosystem", sa.String(length=60), nullable=True),
        sa.Column("source", sa.String(length=200), nullable=True),
        sa.Column("risk_level", sa.String(length=20), nullable=False),
        sa.Column("is_transitive", sa.Boolean(), nullable=False),
        sa.Column("meta", sa.JSON(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            smorx_behavior.db.types.UTCDateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            smorx_behavior.db.types.UTCDateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["repository_id"],
            ["repositories.id"],
            name=op.f("fk_dependencies_repository_id_repositories"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_dependencies")),
    )
    op.create_table(
        "risk_zones",
        sa.Column("repository_id", sa.Uuid(), nullable=False),
        sa.Column("path_pattern", sa.String(length=400), nullable=False),
        sa.Column("reason", sa.Text(), nullable=True),
        sa.Column("severity", sa.String(length=20), nullable=False),
        sa.Column("score", sa.Float(), nullable=False),
        sa.Column("meta", sa.JSON(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            smorx_behavior.db.types.UTCDateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            smorx_behavior.db.types.UTCDateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["repository_id"],
            ["repositories.id"],
            name=op.f("fk_risk_zones_repository_id_repositories"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_risk_zones")),
    )
    op.create_table(
        "behaviors",
        sa.Column("repository_id", sa.Uuid(), nullable=False),
        sa.Column("origin_change_id", sa.Uuid(), nullable=True),
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("category", sa.String(length=60), nullable=True),
        sa.Column("protected", sa.Boolean(), nullable=False),
        sa.Column("signature", sa.Text(), nullable=True),
        sa.Column(
            "discovered_at", smorx_behavior.db.types.UTCDateTime(timezone=True), nullable=True
        ),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("locked", sa.Boolean(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            smorx_behavior.db.types.UTCDateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            smorx_behavior.db.types.UTCDateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["origin_change_id"], ["changes.id"], name=op.f("fk_behaviors_origin_change_id_changes")
        ),
        sa.ForeignKeyConstraint(
            ["repository_id"],
            ["repositories.id"],
            name=op.f("fk_behaviors_repository_id_repositories"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_behaviors")),
    )
    op.create_table(
        "tasks",
        sa.Column("project_id", sa.Uuid(), nullable=False),
        sa.Column("repository_id", sa.Uuid(), nullable=True),
        sa.Column("change_id", sa.Uuid(), nullable=True),
        sa.Column("title", sa.String(length=400), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("status", sa.String(length=40), nullable=False),
        sa.Column("priority", sa.String(length=20), nullable=False),
        sa.Column("requested_by", sa.String(length=120), nullable=True),
        sa.Column("acceptance_criteria", sa.JSON(), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("locked", sa.Boolean(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            smorx_behavior.db.types.UTCDateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            smorx_behavior.db.types.UTCDateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["change_id"], ["changes.id"], name=op.f("fk_tasks_change_id_changes")
        ),
        sa.ForeignKeyConstraint(
            ["project_id"], ["projects.id"], name=op.f("fk_tasks_project_id_projects")
        ),
        sa.ForeignKeyConstraint(
            ["repository_id"], ["repositories.id"], name=op.f("fk_tasks_repository_id_repositories")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_tasks")),
    )
    op.create_table(
        "claims",
        sa.Column("task_id", sa.Uuid(), nullable=True),
        sa.Column("statement", sa.Text(), nullable=False),
        sa.Column("kind", sa.String(length=60), nullable=False),
        sa.Column("status", sa.String(length=40), nullable=False),
        sa.Column("confidence", sa.Float(), nullable=True),
        sa.Column("owner_type", sa.String(length=60), nullable=False),
        sa.Column("owner_id", sa.Uuid(), nullable=True),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("locked", sa.Boolean(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            smorx_behavior.db.types.UTCDateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            smorx_behavior.db.types.UTCDateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["task_id"], ["tasks.id"], name=op.f("fk_claims_task_id_tasks")),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_claims")),
    )
    op.create_table(
        "ghosts",
        sa.Column("repository_id", sa.Uuid(), nullable=False),
        sa.Column("behavior_id", sa.Uuid(), nullable=True),
        sa.Column("source_change_id", sa.Uuid(), nullable=True),
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("hypothetical", sa.Boolean(), nullable=False),
        sa.Column("status", sa.String(length=40), nullable=False),
        sa.Column("payload", sa.JSON(), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            smorx_behavior.db.types.UTCDateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            smorx_behavior.db.types.UTCDateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["behavior_id"], ["behaviors.id"], name=op.f("fk_ghosts_behavior_id_behaviors")
        ),
        sa.ForeignKeyConstraint(
            ["repository_id"],
            ["repositories.id"],
            name=op.f("fk_ghosts_repository_id_repositories"),
        ),
        sa.ForeignKeyConstraint(
            ["source_change_id"], ["changes.id"], name=op.f("fk_ghosts_source_change_id_changes")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_ghosts")),
    )
    op.create_table(
        "intent_ledgers",
        sa.Column("project_id", sa.Uuid(), nullable=False),
        sa.Column("task_id", sa.Uuid(), nullable=True),
        sa.Column("title", sa.String(length=300), nullable=False),
        sa.Column("source", sa.String(length=120), nullable=False),
        sa.Column("status", sa.String(length=40), nullable=False),
        sa.Column("owner_scope", sa.String(length=60), nullable=False),
        sa.Column("created_by", sa.String(length=120), nullable=True),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("locked", sa.Boolean(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            smorx_behavior.db.types.UTCDateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            smorx_behavior.db.types.UTCDateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["project_id"], ["projects.id"], name=op.f("fk_intent_ledgers_project_id_projects")
        ),
        sa.ForeignKeyConstraint(
            ["task_id"], ["tasks.id"], name=op.f("fk_intent_ledgers_task_id_tasks")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_intent_ledgers")),
    )
    op.create_table(
        "invariants",
        sa.Column("behavior_id", sa.Uuid(), nullable=True),
        sa.Column("constitution_claim_id", sa.Uuid(), nullable=True),
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("statement", sa.Text(), nullable=False),
        sa.Column("severity", sa.String(length=20), nullable=False),
        sa.Column("enforced_by", sa.String(length=200), nullable=True),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("locked", sa.Boolean(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            smorx_behavior.db.types.UTCDateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            smorx_behavior.db.types.UTCDateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["behavior_id"], ["behaviors.id"], name=op.f("fk_invariants_behavior_id_behaviors")
        ),
        sa.ForeignKeyConstraint(
            ["constitution_claim_id"],
            ["constitution_claims.id"],
            name=op.f("fk_invariants_constitution_claim_id_constitution_claims"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_invariants")),
    )
    op.create_table(
        "runs",
        sa.Column("task_id", sa.Uuid(), nullable=False),
        sa.Column("kind", sa.String(length=40), nullable=False),
        sa.Column("status", sa.String(length=40), nullable=False),
        sa.Column("summary", sa.Text(), nullable=True),
        sa.Column("started_at", smorx_behavior.db.types.UTCDateTime(timezone=True), nullable=True),
        sa.Column("finished_at", smorx_behavior.db.types.UTCDateTime(timezone=True), nullable=True),
        sa.Column("environment", sa.JSON(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            smorx_behavior.db.types.UTCDateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            smorx_behavior.db.types.UTCDateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["task_id"], ["tasks.id"], name=op.f("fk_runs_task_id_tasks")),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_runs")),
    )
    op.create_table(
        "agent_runs",
        sa.Column("run_id", sa.Uuid(), nullable=False),
        sa.Column("role", sa.String(length=60), nullable=False),
        sa.Column("model", sa.String(length=120), nullable=True),
        sa.Column("provider", sa.String(length=60), nullable=True),
        sa.Column("status", sa.String(length=40), nullable=False),
        sa.Column("state", sa.String(length=40), nullable=False),
        sa.Column("iterations", sa.Integer(), nullable=False),
        sa.Column("max_iterations", sa.Integer(), nullable=False),
        sa.Column("duration_ms", sa.Integer(), nullable=True),
        sa.Column("token_usage", sa.JSON(), nullable=False),
        sa.Column("plan", sa.JSON(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            smorx_behavior.db.types.UTCDateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            smorx_behavior.db.types.UTCDateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["run_id"], ["runs.id"], name=op.f("fk_agent_runs_run_id_runs")),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_agent_runs")),
    )
    op.create_table(
        "consequential_events",
        sa.Column("entity_type", sa.String(length=80), nullable=False),
        sa.Column("entity_id", sa.Uuid(), nullable=False),
        sa.Column("event_type", sa.String(length=60), nullable=False),
        sa.Column("occurred_at", smorx_behavior.db.types.UTCDateTime(timezone=True), nullable=True),
        sa.Column("actor", sa.String(length=120), nullable=True),
        sa.Column("payload", sa.JSON(), nullable=False),
        sa.Column("provenance", sa.Text(), nullable=True),
        sa.Column("task_id", sa.Uuid(), nullable=True),
        sa.Column("run_id", sa.Uuid(), nullable=True),
        sa.Column("sequence", sa.Integer(), nullable=False),
        sa.Column("hash", sa.String(length=64), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            smorx_behavior.db.types.UTCDateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            smorx_behavior.db.types.UTCDateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["run_id"], ["runs.id"], name=op.f("fk_consequential_events_run_id_runs")
        ),
        sa.ForeignKeyConstraint(
            ["task_id"], ["tasks.id"], name=op.f("fk_consequential_events_task_id_tasks")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_consequential_events")),
    )
    op.create_table(
        "intent_items",
        sa.Column("intent_ledger_id", sa.Uuid(), nullable=False),
        sa.Column("task_id", sa.Uuid(), nullable=True),
        sa.Column("statement", sa.Text(), nullable=False),
        sa.Column("kind", sa.String(length=60), nullable=False),
        sa.Column("priority", sa.String(length=20), nullable=False),
        sa.Column("status", sa.String(length=40), nullable=False),
        sa.Column("authorized", sa.Boolean(), nullable=False),
        sa.Column("source_ref", sa.String(length=300), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            smorx_behavior.db.types.UTCDateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            smorx_behavior.db.types.UTCDateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["intent_ledger_id"],
            ["intent_ledgers.id"],
            name=op.f("fk_intent_items_intent_ledger_id_intent_ledgers"),
        ),
        sa.ForeignKeyConstraint(
            ["task_id"], ["tasks.id"], name=op.f("fk_intent_items_task_id_tasks")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_intent_items")),
    )
    op.create_table(
        "verification_plans",
        sa.Column("change_id", sa.Uuid(), nullable=False),
        sa.Column("task_id", sa.Uuid(), nullable=True),
        sa.Column("intent_ledger_id", sa.Uuid(), nullable=True),
        sa.Column("title", sa.String(length=300), nullable=False),
        sa.Column("strategy", sa.JSON(), nullable=False),
        sa.Column("verification_contract", sa.JSON(), nullable=False),
        sa.Column("status", sa.String(length=40), nullable=False),
        sa.Column("owner_scope", sa.String(length=60), nullable=False),
        sa.Column("created_by", sa.String(length=120), nullable=True),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("locked", sa.Boolean(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            smorx_behavior.db.types.UTCDateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            smorx_behavior.db.types.UTCDateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["change_id"], ["changes.id"], name=op.f("fk_verification_plans_change_id_changes")
        ),
        sa.ForeignKeyConstraint(
            ["intent_ledger_id"],
            ["intent_ledgers.id"],
            name=op.f("fk_verification_plans_intent_ledger_id_intent_ledgers"),
        ),
        sa.ForeignKeyConstraint(
            ["task_id"], ["tasks.id"], name=op.f("fk_verification_plans_task_id_tasks")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_verification_plans")),
    )
    op.create_table(
        "candidate_patches",
        sa.Column("change_id", sa.Uuid(), nullable=False),
        sa.Column("task_id", sa.Uuid(), nullable=False),
        sa.Column("agent_run_id", sa.Uuid(), nullable=True),
        sa.Column("base_commit", sa.String(length=64), nullable=True),
        sa.Column("patch_ref", sa.String(length=500), nullable=True),
        sa.Column("diff", sa.Text(), nullable=True),
        sa.Column("files_changed", sa.JSON(), nullable=False),
        sa.Column("summary", sa.Text(), nullable=True),
        sa.Column("status", sa.String(length=40), nullable=False),
        sa.Column("candidate_index", sa.Integer(), nullable=False),
        sa.Column("proposed_by", sa.String(length=120), nullable=True),
        sa.Column("owner_scope", sa.String(length=60), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("locked", sa.Boolean(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            smorx_behavior.db.types.UTCDateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            smorx_behavior.db.types.UTCDateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["agent_run_id"],
            ["agent_runs.id"],
            name=op.f("fk_candidate_patches_agent_run_id_agent_runs"),
        ),
        sa.ForeignKeyConstraint(
            ["change_id"], ["changes.id"], name=op.f("fk_candidate_patches_change_id_changes")
        ),
        sa.ForeignKeyConstraint(
            ["task_id"], ["tasks.id"], name=op.f("fk_candidate_patches_task_id_tasks")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_candidate_patches")),
    )
    op.create_table(
        "semantic_impacts",
        sa.Column("task_id", sa.Uuid(), nullable=False),
        sa.Column("change_id", sa.Uuid(), nullable=True),
        sa.Column("intent_item_id", sa.Uuid(), nullable=True),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("scope", sa.JSON(), nullable=False),
        sa.Column("impacted_behaviors", sa.JSON(), nullable=False),
        sa.Column("impacted_artifacts", sa.JSON(), nullable=False),
        sa.Column("status", sa.String(length=40), nullable=False),
        sa.Column("owner_scope", sa.String(length=60), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("locked", sa.Boolean(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            smorx_behavior.db.types.UTCDateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            smorx_behavior.db.types.UTCDateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["change_id"], ["changes.id"], name=op.f("fk_semantic_impacts_change_id_changes")
        ),
        sa.ForeignKeyConstraint(
            ["intent_item_id"],
            ["intent_items.id"],
            name=op.f("fk_semantic_impacts_intent_item_id_intent_items"),
        ),
        sa.ForeignKeyConstraint(
            ["task_id"], ["tasks.id"], name=op.f("fk_semantic_impacts_task_id_tasks")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_semantic_impacts")),
    )
    op.create_table(
        "subagent_runs",
        sa.Column("agent_run_id", sa.Uuid(), nullable=False),
        sa.Column("name", sa.String(length=120), nullable=False),
        sa.Column("responsibility", sa.Text(), nullable=True),
        sa.Column("status", sa.String(length=40), nullable=False),
        sa.Column("inputs", sa.JSON(), nullable=False),
        sa.Column("outputs", sa.JSON(), nullable=False),
        sa.Column("confidence", sa.Float(), nullable=True),
        sa.Column("evidence_ref", sa.String(length=200), nullable=True),
        sa.Column("started_at", smorx_behavior.db.types.UTCDateTime(timezone=True), nullable=True),
        sa.Column("finished_at", smorx_behavior.db.types.UTCDateTime(timezone=True), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            smorx_behavior.db.types.UTCDateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            smorx_behavior.db.types.UTCDateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["agent_run_id"],
            ["agent_runs.id"],
            name=op.f("fk_subagent_runs_agent_run_id_agent_runs"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_subagent_runs")),
    )
    op.create_table(
        "verification_cases",
        sa.Column("verification_plan_id", sa.Uuid(), nullable=False),
        sa.Column("change_id", sa.Uuid(), nullable=True),
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("kind", sa.String(length=60), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("method", sa.Text(), nullable=True),
        sa.Column("expected", sa.Text(), nullable=True),
        sa.Column("threshold", sa.Float(), nullable=True),
        sa.Column("status", sa.String(length=40), nullable=False),
        sa.Column("independent", sa.Boolean(), nullable=False),
        sa.Column("owning_module", sa.String(length=120), nullable=True),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("locked", sa.Boolean(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            smorx_behavior.db.types.UTCDateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            smorx_behavior.db.types.UTCDateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["change_id"], ["changes.id"], name=op.f("fk_verification_cases_change_id_changes")
        ),
        sa.ForeignKeyConstraint(
            ["verification_plan_id"],
            ["verification_plans.id"],
            name=op.f("fk_verification_cases_verification_plan_id_verification_plans"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_verification_cases")),
    )
    op.create_table(
        "executions",
        sa.Column("run_id", sa.Uuid(), nullable=False),
        sa.Column("agent_run_id", sa.Uuid(), nullable=True),
        sa.Column("change_id", sa.Uuid(), nullable=True),
        sa.Column("candidate_patch_id", sa.Uuid(), nullable=True),
        sa.Column("verification_case_id", sa.Uuid(), nullable=True),
        sa.Column("sandbox_id", sa.String(length=200), nullable=True),
        sa.Column("kind", sa.String(length=60), nullable=False),
        sa.Column("command", sa.Text(), nullable=True),
        sa.Column("cwd", sa.String(length=500), nullable=True),
        sa.Column("exit_code", sa.Integer(), nullable=True),
        sa.Column("stdout", sa.Text(), nullable=True),
        sa.Column("stderr", sa.Text(), nullable=True),
        sa.Column("duration_ms", sa.Integer(), nullable=True),
        sa.Column("status", sa.String(length=40), nullable=False),
        sa.Column("started_at", smorx_behavior.db.types.UTCDateTime(timezone=True), nullable=True),
        sa.Column("finished_at", smorx_behavior.db.types.UTCDateTime(timezone=True), nullable=True),
        sa.Column("environment", sa.JSON(), nullable=False),
        sa.Column("machine_result", sa.JSON(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            smorx_behavior.db.types.UTCDateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            smorx_behavior.db.types.UTCDateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["agent_run_id"], ["agent_runs.id"], name=op.f("fk_executions_agent_run_id_agent_runs")
        ),
        sa.ForeignKeyConstraint(
            ["candidate_patch_id"],
            ["candidate_patches.id"],
            name=op.f("fk_executions_candidate_patch_id_candidate_patches"),
        ),
        sa.ForeignKeyConstraint(
            ["change_id"], ["changes.id"], name=op.f("fk_executions_change_id_changes")
        ),
        sa.ForeignKeyConstraint(["run_id"], ["runs.id"], name=op.f("fk_executions_run_id_runs")),
        sa.ForeignKeyConstraint(
            ["verification_case_id"],
            ["verification_cases.id"],
            name=op.f("fk_executions_verification_case_id_verification_cases"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_executions")),
    )
    op.create_table(
        "evidence",
        sa.Column("task_id", sa.Uuid(), nullable=True),
        sa.Column("run_id", sa.Uuid(), nullable=True),
        sa.Column("agent_run_id", sa.Uuid(), nullable=True),
        sa.Column("subagent_run_id", sa.Uuid(), nullable=True),
        sa.Column("execution_id", sa.Uuid(), nullable=True),
        sa.Column("claim_id", sa.Uuid(), nullable=True),
        sa.Column("verification_case_id", sa.Uuid(), nullable=True),
        sa.Column("type", sa.String(length=60), nullable=False),
        sa.Column("occurred_at", smorx_behavior.db.types.UTCDateTime(timezone=True), nullable=True),
        sa.Column("source", sa.String(length=200), nullable=True),
        sa.Column("provenance", sa.Text(), nullable=True),
        sa.Column("artifact", sa.String(length=500), nullable=True),
        sa.Column("machine_result", sa.JSON(), nullable=False),
        sa.Column("hash", sa.String(length=64), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            smorx_behavior.db.types.UTCDateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            smorx_behavior.db.types.UTCDateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["agent_run_id"], ["agent_runs.id"], name=op.f("fk_evidence_agent_run_id_agent_runs")
        ),
        sa.ForeignKeyConstraint(
            ["claim_id"], ["claims.id"], name=op.f("fk_evidence_claim_id_claims")
        ),
        sa.ForeignKeyConstraint(
            ["execution_id"], ["executions.id"], name=op.f("fk_evidence_execution_id_executions")
        ),
        sa.ForeignKeyConstraint(["run_id"], ["runs.id"], name=op.f("fk_evidence_run_id_runs")),
        sa.ForeignKeyConstraint(
            ["subagent_run_id"],
            ["subagent_runs.id"],
            name=op.f("fk_evidence_subagent_run_id_subagent_runs"),
        ),
        sa.ForeignKeyConstraint(["task_id"], ["tasks.id"], name=op.f("fk_evidence_task_id_tasks")),
        sa.ForeignKeyConstraint(
            ["verification_case_id"],
            ["verification_cases.id"],
            name=op.f("fk_evidence_verification_case_id_verification_cases"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_evidence")),
        sa.UniqueConstraint("hash", name=op.f("uc_evidence_hash")),
    )
    op.create_table(
        "failures",
        sa.Column("execution_id", sa.Uuid(), nullable=True),
        sa.Column("task_id", sa.Uuid(), nullable=True),
        sa.Column("run_id", sa.Uuid(), nullable=True),
        sa.Column("candidate_patch_id", sa.Uuid(), nullable=True),
        sa.Column("evidence_id", sa.Uuid(), nullable=True),
        sa.Column("classification", sa.String(length=60), nullable=False),
        sa.Column("message", sa.Text(), nullable=False),
        sa.Column("probable_cause", sa.Text(), nullable=True),
        sa.Column("next_action", sa.Text(), nullable=True),
        sa.Column("severity", sa.String(length=20), nullable=False),
        sa.Column("iteration", sa.Integer(), nullable=False),
        sa.Column("resolved", sa.Boolean(), nullable=False),
        sa.Column("occurred_at", smorx_behavior.db.types.UTCDateTime(timezone=True), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            smorx_behavior.db.types.UTCDateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            smorx_behavior.db.types.UTCDateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["candidate_patch_id"],
            ["candidate_patches.id"],
            name=op.f("fk_failures_candidate_patch_id_candidate_patches"),
        ),
        sa.ForeignKeyConstraint(
            ["evidence_id"], ["evidence.id"], name=op.f("fk_failures_evidence_id_evidence")
        ),
        sa.ForeignKeyConstraint(
            ["execution_id"], ["executions.id"], name=op.f("fk_failures_execution_id_executions")
        ),
        sa.ForeignKeyConstraint(["run_id"], ["runs.id"], name=op.f("fk_failures_run_id_runs")),
        sa.ForeignKeyConstraint(["task_id"], ["tasks.id"], name=op.f("fk_failures_task_id_tasks")),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_failures")),
    )
    op.create_table(
        "incidents",
        sa.Column("repository_id", sa.Uuid(), nullable=False),
        sa.Column("change_id", sa.Uuid(), nullable=True),
        sa.Column("evidence_id", sa.Uuid(), nullable=True),
        sa.Column("title", sa.String(length=400), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("severity", sa.String(length=20), nullable=False),
        sa.Column("status", sa.String(length=40), nullable=False),
        sa.Column("detected_at", smorx_behavior.db.types.UTCDateTime(timezone=True), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            smorx_behavior.db.types.UTCDateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            smorx_behavior.db.types.UTCDateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["change_id"], ["changes.id"], name=op.f("fk_incidents_change_id_changes")
        ),
        sa.ForeignKeyConstraint(
            ["evidence_id"], ["evidence.id"], name=op.f("fk_incidents_evidence_id_evidence")
        ),
        sa.ForeignKeyConstraint(
            ["repository_id"],
            ["repositories.id"],
            name=op.f("fk_incidents_repository_id_repositories"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_incidents")),
    )
    op.create_table(
        "intent_alignments",
        sa.Column("intent_item_id", sa.Uuid(), nullable=False),
        sa.Column("task_id", sa.Uuid(), nullable=True),
        sa.Column("claim_id", sa.Uuid(), nullable=True),
        sa.Column("change_id", sa.Uuid(), nullable=True),
        sa.Column("evidence_id", sa.Uuid(), nullable=True),
        sa.Column("status", sa.String(length=40), nullable=False),
        sa.Column("verdict", sa.String(length=40), nullable=True),
        sa.Column("rationale", sa.Text(), nullable=True),
        sa.Column("score", sa.Float(), nullable=True),
        sa.Column("verified_by", sa.String(length=120), nullable=True),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("locked", sa.Boolean(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            smorx_behavior.db.types.UTCDateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            smorx_behavior.db.types.UTCDateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["change_id"], ["changes.id"], name=op.f("fk_intent_alignments_change_id_changes")
        ),
        sa.ForeignKeyConstraint(
            ["claim_id"], ["claims.id"], name=op.f("fk_intent_alignments_claim_id_claims")
        ),
        sa.ForeignKeyConstraint(
            ["evidence_id"], ["evidence.id"], name=op.f("fk_intent_alignments_evidence_id_evidence")
        ),
        sa.ForeignKeyConstraint(
            ["intent_item_id"],
            ["intent_items.id"],
            name=op.f("fk_intent_alignments_intent_item_id_intent_items"),
        ),
        sa.ForeignKeyConstraint(
            ["task_id"], ["tasks.id"], name=op.f("fk_intent_alignments_task_id_tasks")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_intent_alignments")),
    )
    op.create_table(
        "certificates",
        sa.Column("task_id", sa.Uuid(), nullable=True),
        sa.Column("project_id", sa.Uuid(), nullable=True),
        sa.Column("claim_id", sa.Uuid(), nullable=True),
        sa.Column("verification_plan_id", sa.Uuid(), nullable=True),
        sa.Column("intent_alignment_id", sa.Uuid(), nullable=True),
        sa.Column("certificate_key", sa.String(length=64), nullable=False),
        sa.Column("status", sa.String(length=40), nullable=False),
        sa.Column("owner_scope", sa.String(length=60), nullable=False),
        sa.Column("signature", sa.String(length=200), nullable=True),
        sa.Column("evidence_hash", sa.String(length=64), nullable=True),
        sa.Column("payload", sa.JSON(), nullable=False),
        sa.Column("issued_at", smorx_behavior.db.types.UTCDateTime(timezone=True), nullable=True),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("locked", sa.Boolean(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            smorx_behavior.db.types.UTCDateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            smorx_behavior.db.types.UTCDateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["claim_id"], ["claims.id"], name=op.f("fk_certificates_claim_id_claims")
        ),
        sa.ForeignKeyConstraint(
            ["intent_alignment_id"],
            ["intent_alignments.id"],
            name=op.f("fk_certificates_intent_alignment_id_intent_alignments"),
        ),
        sa.ForeignKeyConstraint(
            ["project_id"], ["projects.id"], name=op.f("fk_certificates_project_id_projects")
        ),
        sa.ForeignKeyConstraint(
            ["task_id"], ["tasks.id"], name=op.f("fk_certificates_task_id_tasks")
        ),
        sa.ForeignKeyConstraint(
            ["verification_plan_id"],
            ["verification_plans.id"],
            name=op.f("fk_certificates_verification_plan_id_verification_plans"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_certificates")),
        sa.UniqueConstraint("certificate_key", name=op.f("uc_certificates_certificate_key")),
    )
    op.create_table(
        "repair_packages",
        sa.Column("failure_id", sa.Uuid(), nullable=True),
        sa.Column("task_id", sa.Uuid(), nullable=True),
        sa.Column("candidate_patch_id", sa.Uuid(), nullable=True),
        sa.Column("evidence_id", sa.Uuid(), nullable=True),
        sa.Column("attempt", sa.Integer(), nullable=False),
        sa.Column("iteration", sa.Integer(), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("patch_ref", sa.String(length=500), nullable=True),
        sa.Column("status", sa.String(length=40), nullable=False),
        sa.Column("started_at", smorx_behavior.db.types.UTCDateTime(timezone=True), nullable=True),
        sa.Column("finished_at", smorx_behavior.db.types.UTCDateTime(timezone=True), nullable=True),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            smorx_behavior.db.types.UTCDateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            smorx_behavior.db.types.UTCDateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["candidate_patch_id"],
            ["candidate_patches.id"],
            name=op.f("fk_repair_packages_candidate_patch_id_candidate_patches"),
        ),
        sa.ForeignKeyConstraint(
            ["evidence_id"], ["evidence.id"], name=op.f("fk_repair_packages_evidence_id_evidence")
        ),
        sa.ForeignKeyConstraint(
            ["failure_id"], ["failures.id"], name=op.f("fk_repair_packages_failure_id_failures")
        ),
        sa.ForeignKeyConstraint(
            ["task_id"], ["tasks.id"], name=op.f("fk_repair_packages_task_id_tasks")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_repair_packages")),
    )
    op.create_table(
        "behavioral_deltas",
        sa.Column("task_id", sa.Uuid(), nullable=True),
        sa.Column("change_id", sa.Uuid(), nullable=True),
        sa.Column("claim_id", sa.Uuid(), nullable=True),
        sa.Column("behavior_id", sa.Uuid(), nullable=True),
        sa.Column("execution_id", sa.Uuid(), nullable=True),
        sa.Column("evidence_id", sa.Uuid(), nullable=True),
        sa.Column("certificate_id", sa.Uuid(), nullable=True),
        sa.Column("metric", sa.String(length=200), nullable=True),
        sa.Column("baseline_value", sa.String(length=200), nullable=True),
        sa.Column("candidate_value", sa.String(length=200), nullable=True),
        sa.Column("magnitude", sa.Float(), nullable=True),
        sa.Column("direction", sa.String(length=20), nullable=False),
        sa.Column("category", sa.String(length=60), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("observed", sa.Boolean(), nullable=False),
        sa.Column("owner_scope", sa.String(length=60), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            smorx_behavior.db.types.UTCDateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            smorx_behavior.db.types.UTCDateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["behavior_id"],
            ["behaviors.id"],
            name=op.f("fk_behavioral_deltas_behavior_id_behaviors"),
        ),
        sa.ForeignKeyConstraint(
            ["certificate_id"],
            ["certificates.id"],
            name=op.f("fk_behavioral_deltas_certificate_id_certificates"),
        ),
        sa.ForeignKeyConstraint(
            ["change_id"], ["changes.id"], name=op.f("fk_behavioral_deltas_change_id_changes")
        ),
        sa.ForeignKeyConstraint(
            ["claim_id"], ["claims.id"], name=op.f("fk_behavioral_deltas_claim_id_claims")
        ),
        sa.ForeignKeyConstraint(
            ["evidence_id"], ["evidence.id"], name=op.f("fk_behavioral_deltas_evidence_id_evidence")
        ),
        sa.ForeignKeyConstraint(
            ["execution_id"],
            ["executions.id"],
            name=op.f("fk_behavioral_deltas_execution_id_executions"),
        ),
        sa.ForeignKeyConstraint(
            ["task_id"], ["tasks.id"], name=op.f("fk_behavioral_deltas_task_id_tasks")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_behavioral_deltas")),
    )
    op.create_table(
        "memory_updates",
        sa.Column("project_id", sa.Uuid(), nullable=False),
        sa.Column("certificate_id", sa.Uuid(), nullable=True),
        sa.Column("task_id", sa.Uuid(), nullable=True),
        sa.Column("evidence_id", sa.Uuid(), nullable=True),
        sa.Column("kind", sa.String(length=60), nullable=False),
        sa.Column("summary", sa.Text(), nullable=True),
        sa.Column("content", sa.JSON(), nullable=False),
        sa.Column("applied", sa.Boolean(), nullable=False),
        sa.Column("created_by", sa.String(length=120), nullable=True),
        sa.Column("memory_ref", sa.String(length=300), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            smorx_behavior.db.types.UTCDateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            smorx_behavior.db.types.UTCDateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["certificate_id"],
            ["certificates.id"],
            name=op.f("fk_memory_updates_certificate_id_certificates"),
        ),
        sa.ForeignKeyConstraint(
            ["evidence_id"], ["evidence.id"], name=op.f("fk_memory_updates_evidence_id_evidence")
        ),
        sa.ForeignKeyConstraint(
            ["project_id"], ["projects.id"], name=op.f("fk_memory_updates_project_id_projects")
        ),
        sa.ForeignKeyConstraint(
            ["task_id"], ["tasks.id"], name=op.f("fk_memory_updates_task_id_tasks")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_memory_updates")),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("memory_updates")
    op.drop_table("behavioral_deltas")
    op.drop_table("repair_packages")
    op.drop_table("certificates")
    op.drop_table("intent_alignments")
    op.drop_table("incidents")
    op.drop_table("failures")
    op.drop_table("evidence")
    op.drop_table("executions")
    op.drop_table("verification_cases")
    op.drop_table("subagent_runs")
    op.drop_table("semantic_impacts")
    op.drop_table("candidate_patches")
    op.drop_table("verification_plans")
    op.drop_table("intent_items")
    op.drop_table("consequential_events")
    op.drop_table("agent_runs")
    op.drop_table("runs")
    op.drop_table("invariants")
    op.drop_table("intent_ledgers")
    op.drop_table("ghosts")
    op.drop_table("claims")
    op.drop_table("tasks")
    op.drop_table("behaviors")
    op.drop_table("risk_zones")
    op.drop_table("dependencies")
    op.drop_table("constitution_claims")
    op.drop_table("changes")
    op.drop_table("repositories")
    op.drop_table("constitutions")
    op.drop_table("projects")
    # ### end Alembic commands ###
