"""Secret scanner for the Software Evolution Intelligence System repository.

Importable module (public API ``scan_secrets``) and a runnable CLI:

    python scripts/scan_secrets.py [--root PATH] [--json]

Exits ``0`` when no findings exist and ``1`` when findings are reported.

Every reported snippet is redacted: the matched secret value is replaced with
``***`` so the tool never echoes a real credential. Placeholder values that
follow an ``=`` with empty/whitespace (e.g. ``NEBIUS_API_KEY=`` lines in
``.env.example``) are never flagged. Bare ``NAME=value`` assignments are only
flagged when the variable name is env-var style (all-caps, e.g.
``NEBIUS_API_KEY``); lowercase kwargs such as ``api_key=<reference>`` in
application code are intentionally not flagged.
"""

from __future__ import annotations

import argparse
import json
import os
import re
import sys
from collections.abc import Sequence
from dataclasses import asdict, dataclass
from pathlib import Path

_SKIP_DIR_NAMES = frozenset(
    {
        ".git",
        ".venv",
        "venv",
        "node_modules",
        "__pycache__",
        ".mypy_cache",
        ".ruff_cache",
        ".pytest_cache",
        ".next",
        "dist",
        "build",
        ".recon",  # gitignored local agent cache regenerated by tooling
    }
)

_SKIP_FILE_SUFFIXES = frozenset({".pyc", ".lock", ".json"})

_TEXT_SUFFIXES = frozenset(
    {
        ".py",
        ".pyi",
        ".ts",
        ".tsx",
        ".js",
        ".jsx",
        ".mjs",
        ".cjs",
        ".md",
        ".mdx",
        ".txt",
        ".toml",
        ".ini",
        ".cfg",
        ".conf",
        ".yaml",
        ".yml",
        ".sh",
        ".bash",
        ".ps1",
        ".psm1",
        ".bat",
        ".cmd",
        ".css",
        ".html",
        ".htm",
        ".sql",
        ".graphql",
    }
)

_TEXT_NAMES = frozenset(
    {
        ".env.example",
        ".gitignore",
        ".gitattributes",
        ".dockerignore",
        ".editorconfig",
        "Dockerfile",
        "Makefile",
    }
)

# Rule set. A ``value`` named group is required on every pattern so the
# finding snippet can redact exactly the matched secret.
#
# The bare ``NAME=value`` rule is intentionally uppercase-only on the variable
# side. A broader, case-insensitive rule flags ordinary Python kwargs such as
# ``api_key=<reference>`` in real application code, producing permanent false
# positives in the security gate. Env-variable style assignments (e.g.
# ``NEBIUS_API_KEY=sk-...``, ``AWS_SECRET_ACCESS_KEY=...``) are all-caps and
# remain covered.
_NEBIUS_API = re.compile(
    r"NEBIUS_API_KEY\s*=\s*(?P<value>[A-Za-z0-9._-]{8,})", re.IGNORECASE
)
_ENV_SECRET_ASSIGN = re.compile(
    r"(?P<name>[A-Z][A-Z0-9_]*_(?:KEY|SECRET|TOKEN|PASSWORD))\s*=\s*(?P<value>[A-Za-z0-9._-]{8,})"
)
_BEARER_AUTH = re.compile(
    r"(?:authorization|bearer)\s*[:=]\s*[\"'](?P<value>[^\"']{8,})", re.IGNORECASE
)
_PEM_PATTERN = re.compile(r"(?P<value>-----BEGIN (?:(?:RSA |EC )?PRIVATE KEY)-----)")
_API_PATTERN = re.compile(
    r"api[_-]?key\s*[:=]\s*[\"'](?P<value>[A-Za-z0-9_-]{16,})", re.IGNORECASE
)

_RULES: tuple[tuple[str, re.Pattern[str]], ...] = (
    ("secret-assign", _NEBIUS_API),
    ("secret-assign", _ENV_SECRET_ASSIGN),
    ("bearer-auth", _BEARER_AUTH),
    ("private-key", _PEM_PATTERN),
    ("api-key", _API_PATTERN),
)


@dataclass
class Finding:
    path: str
    line: int
    rule: str
    snippet: str


def _skippable_file(path: Path) -> bool:
    name = path.name.lower()
    if path.suffix.lower() in _SKIP_FILE_SUFFIXES:
        return True
    if name == ".env" or (name.startswith(".env.") and name != ".env.example"):
        return True
    if name in _TEXT_NAMES:
        return False
    return path.suffix.lower() not in _TEXT_SUFFIXES


def _redact_snippet(match: re.Match[str], raw_line: str) -> str:
    value = match.group("value")
    return raw_line.strip().replace(value, "***")


def _scan_text(path: Path, repo_root: Path, findings: list[Finding]) -> None:
    try:
        with path.open("r", encoding="utf-8", errors="replace") as handle:
            lines = handle.readlines()
    except OSError:
        return
    for line_no, raw_line in enumerate(lines, start=1):
        for rule_name, pattern in _RULES:
            for match in pattern.finditer(raw_line):
                findings.append(
                    Finding(
                        path=str(path.relative_to(repo_root)),
                        line=line_no,
                        rule=rule_name,
                        snippet=_redact_snippet(match, raw_line),
                    )
                )


def scan_secrets(repo_root: Path, *, ignore_dirs: Sequence[str] = ()) -> list[Finding]:
    """Recursively scan a repository for hardcoded credentials.

    The value portion of every finding is masked with ``***`` in the snippet.
    """
    root = Path(repo_root)
    skip_dirs = frozenset(_SKIP_DIR_NAMES) | {entry for entry in ignore_dirs}
    findings: list[Finding] = []
    for dirpath, dirnames, filenames in os.walk(root):
        dirnames[:] = [
            entry
            for entry in dirnames
            if entry not in skip_dirs and entry.upper() != "NUL"
        ]
        for filename in filenames:
            if filename.upper() == "NUL":
                continue
            path = Path(dirpath) / filename
            if _skippable_file(path):
                continue
            _scan_text(path, root, findings)
    return findings


def main(argv: Sequence[str] | None = None) -> int:
    parser = argparse.ArgumentParser(
        description="Scan the repository for hardcoded secrets."
    )
    parser.add_argument("--root", default=".", help="repository root to scan")
    parser.add_argument("--json", action="store_true", help="emit JSON report")
    args = parser.parse_args(argv)

    findings = scan_secrets(Path(args.root))
    if args.json:
        print(json.dumps([asdict(finding) for finding in findings], indent=2))
    for finding in findings:
        print(f"[{finding.rule}] {finding.path}:{finding.line}: {finding.snippet}")
    if not findings:
        print(f"No secrets found in {args.root}")
    return 1 if findings else 0


if __name__ == "__main__":
    raise SystemExit(main(sys.argv[1:]))
