"""Behavioral data model package.

Exports every SQLAlchemy 2.0 ORM entity in Phase 2 (implementation plan
§2.1), the §2.4 structured-event table, the version/lock schema mixin, and the
canonical enum vocabulary. Importing this package registers every table on
``smorx_behavior.db.base.Base.metadata``.
"""

from __future__ import annotations

from smorx_behavior.db.base import Base
from smorx_behavior.models.entities import (
    AgentRun,
    Behavior,
    BehavioralDelta,
    CandidatePatch,
    Certificate,
    Change,
    Claim,
    ConsequentialEvent,
    Constitution,
    ConstitutionClaim,
    Dependency,
    Evidence,
    Execution,
    Failure,
    Ghost,
    ImmutableObjectMixin,
    Incident,
    IntentAlignment,
    IntentItem,
    IntentLedger,
    Invariant,
    MemoryUpdate,
    Project,
    RepairPackage,
    Repository,
    RiskZone,
    Run,
    SemanticImpact,
    SubagentRun,
    Task,
    VerificationCase,
    VerificationPlan,
)
from smorx_behavior.models.enums import (
    AgentState,
    CertificateStatus,
    ClaimStatus,
    ConstitutionStatus,
    DeltaDirection,
    EventKind,
    EvidenceType,
    FailureKind,
    IntentAlignmentStatus,
    IntentKind,
    IntentStatus,
    LockState,
    MemoryKind,
    Priority,
    RepairStatus,
    RunStatus,
    Severity,
    TaskStatus,
    VerificationStatus,
)

__all__ = [
    "AgentRun",
    "AgentState",
    "Base",
    "Behavior",
    "BehavioralDelta",
    "CandidatePatch",
    "Certificate",
    "CertificateStatus",
    "Change",
    "Claim",
    "ClaimStatus",
    "ConsequentialEvent",
    "Constitution",
    "ConstitutionClaim",
    "ConstitutionStatus",
    "DeltaDirection",
    "Dependency",
    "EventKind",
    "Evidence",
    "EvidenceType",
    "Execution",
    "Failure",
    "FailureKind",
    "Ghost",
    "ImmutableObjectMixin",
    "Incident",
    "IntentAlignment",
    "IntentAlignmentStatus",
    "IntentItem",
    "IntentKind",
    "IntentLedger",
    "IntentStatus",
    "Invariant",
    "LockState",
    "MemoryKind",
    "MemoryUpdate",
    "Priority",
    "Project",
    "RepairPackage",
    "RepairStatus",
    "Repository",
    "RiskZone",
    "Run",
    "RunStatus",
    "SemanticImpact",
    "Severity",
    "SubagentRun",
    "Task",
    "TaskStatus",
    "VerificationCase",
    "VerificationPlan",
    "VerificationStatus",
]
